@echo off
echo Starting Discord Bot...
if not exist venv (
    echo Creating virtual environment...
    python -m venv venv
)
call venv\Scripts\activate.bat
echo Installing dependencies...
pip install -r requirements.txt
echo Launching Bot...
python -m bot.main
pause
